import*as THREE from'three';
export class WarehouseScene{
  constructor(el){this.el=el;this.slots=new Map();this.goods=new Map();this.agents=[];this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x101b18);this.camera=new THREE.PerspectiveCamera(50,el.clientWidth/el.clientHeight,.1,100);this.camera.position.set(11,10,14);this.camera.lookAt(0,2,0);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(el.clientWidth,el.clientHeight);this.renderer.shadowMap.enabled=true;el.appendChild(this.renderer.domElement);this.scene.add(new THREE.HemisphereLight(0xdfffea,0x26352f,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(5,12,6);light.castShadow=true;this.scene.add(light);this.build();this.resize=()=>{this.camera.aspect=el.clientWidth/el.clientHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(el.clientWidth,el.clientHeight)};window.addEventListener('resize',this.resize);this.animate()}
  build(){const floor=new THREE.Mesh(new THREE.PlaneGeometry(22,16),new THREE.MeshStandardMaterial({color:0x25342f,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;this.scene.add(floor);for(let r=0;r<3;r++){const z=-5+r*5;for(let level=0;level<3;level++){const shelf=new THREE.Mesh(new THREE.BoxGeometry(16,.12,1.7),new THREE.MeshStandardMaterial({color:0x60736b,metalness:.5}));shelf.position.set(0,.7+level*1.6,z);this.scene.add(shelf)}for(const x of[-8,8]){const post=new THREE.Mesh(new THREE.BoxGeometry(.14,5.2,.14),new THREE.MeshStandardMaterial({color:0x8a9b94}));post.position.set(x,2.6,z);this.scene.add(post)}}}
  syncSlots(rows){rows.forEach((s,i)=>{if(!this.slots.has(s.code)){const rack=Math.floor(i/12),local=i%12,col=local%4,level=Math.floor(local/4);const marker=new THREE.Mesh(new THREE.BoxGeometry(3.6,.08,1.45),new THREE.MeshStandardMaterial({color:0x82918b,transparent:true,opacity:.45}));marker.position.set(-5.9+col*3.9,.82+level*1.6,-5+rack*5);this.scene.add(marker);this.slots.set(s.code,marker)}this.updateSlot(s.code,s.status,s.cargoType)})}
  updateSlot(code,status,cargoType){const slot=this.slots.get(code);if(!slot)return;slot.material.color.set(status==='ABNORMAL'?0xe74c3c:status==='OCCUPIED'?0x2fb879:0x76847e);if(status==='OCCUPIED'&&!this.goods.has(code)){const box=new THREE.Mesh(new THREE.BoxGeometry(1.7,1.05,1.1),new THREE.MeshStandardMaterial({color:cargoType==='pallet'?0xc59b65:0xd89a48}));box.position.copy(slot.position);box.position.y+=.58;box.castShadow=true;this.scene.add(box);this.goods.set(code,box)}else if(status!=='OCCUPIED'&&this.goods.has(code)){this.scene.remove(this.goods.get(code));this.goods.delete(code)}}
  updateAgents(objects=[]){this.agents.forEach(x=>this.scene.remove(x));this.agents=[];objects.filter(x=>['person','forklift'].includes(x.className)).forEach((o,i)=>{const person=o.className==='person',mesh=new THREE.Mesh(person?new THREE.CapsuleGeometry(.25,.8):new THREE.BoxGeometry(1.4,.8,2),new THREE.MeshStandardMaterial({color:person?0x58a6ff:0xffb347}));mesh.position.set(-4+i*2,person?.7:.5,2.5);this.scene.add(mesh);this.agents.push(mesh)})}
  animate(){this.frame=requestAnimationFrame(()=>this.animate());this.renderer.render(this.scene,this.camera)}
  dispose(){cancelAnimationFrame(this.frame);window.removeEventListener('resize',this.resize);this.renderer.dispose();this.el.innerHTML=''}
}
